<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MerchandisingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchandisingRepository extends EntityRepository
{
}
