<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Client;
use AppBundle\Entity\PointVente;
/**
 * RapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportRepository extends EntityRepository
{
	/**
Nombre de point de vente visités
 */
  public function findByType(Client $client=null,$region=null, $startDate=null, $endDate=null,PointVente $pointVente=null){

        $qb = $this->createQueryBuilder('r')->join('r.pointVente','p');
        if($region!=null){
           $qb->where('p.type=:type')
          ->setParameter('type', $region);
          }
      if($startDate!=null){
           $qb->andWhere('r.date>=:startDate')
          ->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
           $qb->andWhere('r.date<=:endDate')
          ->setParameter('endDate',new \DateTime($endDate));
          } 
         return $qb->getQuery()->getArrayResult();  
   
  }
}
