<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StituationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationRepository extends EntityRepository
{
		/*
for mobile
*/
  public function findApercu ($type=null, $startDate=null, $endDate=null){

	  $qb = $this->createQueryBuilder('s')->join('s.rapport','r')->join('r.pointVente','p');
        if($type!=null){
           $qb->where('p.type=:type')
          ->setParameter('type', $type);
          }
          if($startDate!=null){
           $qb->andWhere('r.date>=:startDate')->setParameter('startDate', new \DateTime($startDate));
          }
          if($endDate!=null){
           $qb->andWhere('r.date<=:endDate')->setParameter('endDate',new \DateTime($endDate));
          }
           $qb->select('s.marque as nom'); 
           $qb->addSelect('count(s.frigo) as frigo'); 
           $qb->addSelect('count(s.affiche) as affiche'); 
           $qb->addSelect('count(s.potence) as potence'); 
           $qb->addSelect('count(s.ncp) as ncp');
           $qb->addSelect('count(s.inbar) as inbar'); 
           $qb->addSelect('count(s.id) as nombre'); 
           $qb->addSelect('sum(s.bnreBlle) as bnreblle'); 
           $qb->addSelect('max(s.price) as maxprice'); 
           $qb->addSelect('avg(s.price) as prixmoyen'); 
          $qb->addGroupBy('s.marque');     
          return $qb->getQuery()->getArrayResult();
  }
}
