gagnant_index:
    path:     /
    defaults: { _controller: "AppBundle:Gagnant:index" }
    methods:  GET

gagnant_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Gagnant:show" }
    methods:  GET

gagnant_new:
    path:     /new
    defaults: { _controller: "AppBundle:Gagnant:new" }
    methods:  [GET, POST]

gagnant_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Gagnant:edit" }
    methods:  [GET, POST]

gagnant_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Gagnant:delete" }
    methods:  DELETE
