rapport_index:
    path:     /?section={section}
    defaults: { _controller: "AppBundle:Rapport:index", section:'sales'}
    methods:  GET

rapport_sales:
    path:     /sales
    defaults: { _controller: "AppBundle:Rapport:sales"}
    methods:  GET

rapport_prices:
    path:     /prices
    defaults: { _controller: "AppBundle:Rapport:prices"}
    methods:  GET

rapport_shares:
    path:     /shares
    defaults: { _controller: "AppBundle:Rapport:shares"}
    methods:  GET

rapport_visibilitie:
    path:     /visibilitie
    defaults: { _controller: "AppBundle:Rapport:visibilitie"}
    methods:  GET

rapport_gagnants:
    path:     /gagnants
    defaults: { _controller: "AppBundle:Rapport:gagnants"}
    methods:  GET
    

rapport_apercu_periode:
    path:     /apercu/periode
    defaults: { _controller: "AppBundle:Rapport:apercuPeriode"}
    methods:  GET

rapport_apercu_dernier:
    path:     /apercu/dernier
    defaults: { _controller: "AppBundle:Rapport:apercuDernier"}
    methods:  GET

rapport_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Rapport:show" }
    methods:  GET



