rh_index:
    path:     /
    defaults: { _controller: "AppBundle:RH:index" }
    methods:  GET

rh_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:RH:show" }
    methods:  GET

rh_new:
    path:     /new
    defaults: { _controller: "AppBundle:RH:new" }
    methods:  [GET, POST]

rh_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:RH:edit" }
    methods:  [GET, POST]

rh_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:RH:delete" }
    methods:  DELETE
