
app_produit:
    resource: "@AppBundle/Resources/config/routing/rapport.yml"
    prefix:   /rapport


app_point_vente:
    resource: "@AppBundle/Resources/config/routing/pointvente.yml"
    prefix:   /pointvente

app_gagnant:
    resource: "@AppBundle/Resources/config/routing/gagnant.yml"
    prefix:   /gagnant
    
app_rh:
    resource: "@AppBundle/Resources/config/routing/rh.yml"
    prefix:   /rh

app_control:
    resource: "@AppBundle/Resources/config/routing/etape.yml"
    prefix:   /etape

point_ventes:
    path:      /mobile/points/ventes
    defaults: { _controller: "AppBundle:Mobile:pointVentes" }
    methods:  GET

produits:
    path:      /mobile/produits
    defaults: { _controller: "AppBundle:Mobile:produits" }
    methods:  GET

create_point_ventes:
    path:      /mobile/create/points/ventes
    defaults: { _controller: "AppBundle:Mobile:createPointVentes" }
    methods:  [POST,GET]

create_visites:
    path:      /mobile/create/visites
    defaults: { _controller: "AppBundle:Mobile:createVisites" }
    methods:  POST

create_etatpes:
    path:      /mobile/create/etapes
    defaults: { _controller: "AppBundle:Mobile:createEtapes" }
    methods:  POST 

secteurs:
    path:      /mobile/secteurs/{region}
    defaults: { _controller: "AppBundle:Mobile:secteurs" }
    methods:  GET 

quartiers:
    path:      /mobile/quartiers
    defaults: { _controller: "AppBundle:Mobile:quartiers" }
    methods:  GET 

rhs:
    path:      /mobile/rhs
    defaults: { _controller: "AppBundle:Mobile:rhs" }
    methods:  GET

create_token:
    path:      /mobile/create/auth-token
    defaults: { _controller: "AppBundle:Mobile:postAuthTokens" }
    methods:  POST